### ISSUE TITLE
Allow 'on_startup' block to be defined at module root level

### ISSUE THREAD

**Issue by JakobGM** [JakobGM/astrality#13]
The ``on_startup`` block is by far the most common action block, so we should allow modules to define "on startup" actions at the root indentation level of a module. This results in flatter structures for the most common type of modules.

*Required syntax right now:*
```yaml
module/my_module:
  on_startup:
    run:
      shell: 'echo "Hi!"'

  on_exit:
    run: 
      shell: './cleanup.sh'
```

*We should support:*
```yaml
module/my_module:
  run:
    shell: 'echo "Hi!"'

  on_exit:
    run:
      shell: './cleanup.sh'
```
