### ISSUE TITLE
Dynamically reload kitty configuration file

### ISSUE THREAD

**Issue by bthiebault** [JakobGM/astrality#143]
As stated on the [developer's github](https://github.com/kovidgoyal/kitty/issues/635), Kitty does not and will not provide the function to reload its configuration file without restarting it.

However, there is a workaround to make astrality do it. The requirement is to execute kitty using the following command line:

`kitty --single-instance`

Then, create a kitty module.yml:

```
kitty:
    requires:
        - installed: kitty

    on_startup:
        compile:
            - content: kitty.conf.template
              target: ~/.config/kitty/kitty.conf
        run:
            - shell: kitty @ set-colors --all --configured ~/.config/kitty/kitty.conf

    on_modified:
        modules/kitty/kitty.conf.template:
            compile:
                - content: kitty.conf.template
                  target: ~/.config/kitty/kitty.conf
            run:
                - shell: kitty @ set-colors --all --configured ~/.config/kitty/kitty.conf
```
