### ISSUE TITLE
Add 'only_once' action block or 'requires' parameter to actions

### ISSUE THREAD

**Issue by JakobGM** [JakobGM/astrality#15]
It would be nice to be able to specify actions that only need to be executed once, and never again. Something along the lines of:

```yaml
module/neovim:
  only_once:
    run:
      shell: pacman -S neovim

  on_startup:
    compile:
      source: init.vim
      target: $XDG_CONFIG_HOME/nvim/init.vim
```

We could save the actions that have been run in ``$XDG_DATA_DIR/astrality/only_once.xxx``, perhaps even use [this pypi module](http://pyxdg.readthedocs.io/en/latest/basedirectory.html#data-directories). If we end up using that package (unecessary extra dependency?), we could also replace all ``$XDG_CONFIG_HOME`` logic in the rest of the stack.

The difficulty would be to decide on a practical data format. Then load that data format and compare ``only_once`` actions to items in that file. Perhaps use hashes? And/or datestamp each entry in the file?

Alternatively, we could add ``requires`` parameters to all action types, which would provide the same capabilities. That would be *super* easy to implement, as we could reuse the logic in ``astrality.requirements.Requirement``. Estimated time cost: 10 minutes of implementation, 1 hour of testing.

This would result in something like:

```yaml
module/neovim:
  on_startup:
    run:
      - shell: pacman -S neovim
        requires:
          installed: '!neovim'
    compile:
      source: init.vim
      target: $XDG_CONFIG_HOME/nvim/init.vim
```

The ``!`` negates the requirement, and must be implemented (should not be too difficult).
