### ISSUE TITLE
Module dependencies on other modules

### ISSUE THREAD

**Issue by sshashank124** [JakobGM/astrality#17]
Feature suggestion for adding another keyword to the `requires` section to conditionally enable modules if certain required modules are enabled. Something along the lines of:

```
module/compton:
    requires:
        - installed: compton
        - env: DISPLAY
        - module: xorg         <---- compton depends on the xorg module being enabled
```

This will depend on the order that the modules are declared in. The user will be required to declare modules that are needed by others before the others are declared. This is fine since circular dependencies wouldn't make sense in this case.
