### ISSUE TITLE
Support for executable templates

### ISSUE THREAD

**Issue by sshashank124** [JakobGM/astrality#2]
Are there any current or future plans to add support for setting certain metadata values of the result files generated from the templates. For example, in the case of bspwm's configuration file (bspwmrc) or certain shell scripts that I use, I would like to be able to make the generated files executable (and maybe eventually set specific file permissions). Since the templates are read, populated and then written out to a new file, metadata information such as file permissions (drwxrwxrwx) are lost.

Currently, I am using the following piece of code to achieve this:
`os.chmod(filename, os.stat(filename).st_mode | stat.S_IEXEC)`

It would be great if there was a way to either specify certain file permissions that one wishes to set for a file or to apply the same file permissions as the template file to the generated file

**Comment by JakobGM** [comment]
Hi, @sshashank124!

Thanks for opening this issue! I agree, this would be a nice-to-have feature. I have added a new optional ``permissions`` option to the ``compile`` action in version ``v0.6`` of Astrality. It allows you to set the octal permission bits of the compiled template. For instance ``0o777`` or ``'777'``. 

Read more about it [here](https://astrality.readthedocs.io/en/latest/modules.html#compile-templates).

Example use:

```yaml
module/scripts:
    on_startup:
        compile:
            template: 'script.template'
            target: '/usr/local/bin'
            permissions: '555'
```

You should be able to use the new feature after having run ``pip install --upgrade astrality``.

Although this allows you to set the permission bits *exactly*, it does not allow you to just ``OR`` the permission bit on top of the existing permission bits (whatever they might be), as in your example. I could add an additional ``executable`` flag to the ``compile`` action, which does exactly what you have written above, if you think that should be available. The drawback is yet another configuration option which might confuse people reading the documentation.

It should be said that changing the permissions of the compiled template can also be done by using a ``run`` action:

```yaml
module/scripts:
    on_startup:
        compile:
            template: 'template/path'
        run: 'chmod +x {template/path}'
```

Please let me know if this works for you, and don't hesitate with any future feature requests and/or bug reports ;)
